name: Build and Push Backend Docker Image to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-and-push-backend-to-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Docker environment
        run: |
          docker version
          docker info

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for  Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/apiV1:latest -f Dockerfile .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/apiV1:latest ${{ secrets.DOCKERHUB_USERNAME }}/apiV1:latest
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/apiV1:latest
