name: Deploy Frontend to S3

on:
    workflow_dispatch:

jobs:
  deploy-frontend-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: debug
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "
          
          
          
          
          
          
          
          working directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo ${{ secrets.VITE_API_URL }}
          
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build React frontend
        run: VITE_API_URL=${{ secrets.VITE_API_URL }} npm run build
        working-directory: ./frontend

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          REGION=ap-south-1 # Change to your desired region

          # Check if the bucket exists
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket does not exist. Creating $BUCKET_NAME..."
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION" \
              --create-bucket-configuration LocationConstraint="$REGION"
          else
            echo "Bucket $BUCKET_NAME already exists."
          fi 
          aws s3 sync ./frontend/dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
          aws s3 website s3://${{ secrets.S3_BUCKET_NAME }}/ --index-document index.html --error-document index.html
